package io.github.verybigsad.pimobile.network

enum class NetworkError {
    MALFORMED_URI,
    MALFORMED_JSON,
    INVITATION_INVALID,
    INVITATION_EXPIRED,
    INVITATION_REPLAYED,
    INVALID_SIGNATURE,
    CHALLENGE_INVALID,
    CHALLENGE_EXPIRED,
    CHALLENGE_REPLAYED,
    REPLAY_CACHE_FULL,
    CERTIFICATE_PIN_MISMATCH,
    CERTIFICATE_PROFILE_INVALID,
    TLS_HANDSHAKE_FAILED,
    EXPORTER_UNSUPPORTED,
    WEBSOCKET_HANDSHAKE_FAILED,
    WEBSOCKET_PROTOCOL_ERROR,
    TRANSPORT_EXHAUSTED,
    TRANSPORT_CLOSED,
    PATHS_FAILED,
    STATE_TRANSITION_INVALID,
    RELAY_PAIRING_CONFLICT,
    RELAY_PAIRING_RATE_LIMITED,
    RELAY_PAIRING_UNAVAILABLE,
    RELAY_PAIRING_NOT_READY,
    RELAY_PAIRING_FAILED,
}

class NetworkException(
    val code: NetworkError,
    message: String,
    cause: Throwable? = null,
) : Exception(message, cause)
