package io.github.verybigsad.pimobile.update

/** Stable machine-readable error codes. Never rename; append-only. */
object UpdateError {
    const val DISABLED = "UPDATE_DISABLED"
    const val METADATA_FETCH_FAILED = "UPDATE_METADATA_FETCH_FAILED"
    const val METADATA_TOO_LARGE = "UPDATE_METADATA_TOO_LARGE"
    const val METADATA_INVALID = "UPDATE_METADATA_INVALID"
    const val METADATA_UNTRUSTED = "UPDATE_METADATA_UNTRUSTED"
    const val NO_NEW_VERSION = "UPDATE_NO_NEW_VERSION"
    const val METERED_CONFIRM_REQUIRED = "UPDATE_METERED_CONFIRM_REQUIRED"
    const val INSTALL_PERMISSION_REQUIRED = "UPDATE_INSTALL_PERMISSION_REQUIRED"
    const val DOWNLOAD_FAILED = "UPDATE_DOWNLOAD_FAILED"
    const val DOWNLOAD_SIZE_MISMATCH = "UPDATE_DOWNLOAD_SIZE_MISMATCH"
    const val DOWNLOAD_HASH_MISMATCH = "UPDATE_DOWNLOAD_HASH_MISMATCH"
    const val DOWNLOAD_INSUFFICIENT_SPACE = "UPDATE_DOWNLOAD_INSUFFICIENT_SPACE"
    const val SIGNATURE_MISMATCH = "UPDATE_SIGNATURE_MISMATCH"
    const val SIGNATURE_UNREADABLE = "UPDATE_SIGNATURE_UNREADABLE"
    const val AUTHORIZATION_MISMATCH = "UPDATE_AUTHORIZATION_MISMATCH"
    const val NOT_VERIFIED = "UPDATE_NOT_VERIFIED"
    const val STAGING_FAILED = "UPDATE_STAGING_FAILED"
    const val SESSION_ABANDONED = "UPDATE_SESSION_ABANDONED"
    const val INSTALL_FAILED = "UPDATE_INSTALL_FAILED"
    const val INSTALL_CANCELLED = "UPDATE_INSTALL_CANCELLED"
    const val USER_ACTION_REQUIRED = "UPDATE_USER_ACTION_REQUIRED"
}

class UpdateException(val code: String, message: String, cause: Throwable? = null) : Exception(message, cause)
