version: "2"
linters:
  default: standard
  enable:
    - bodyclose
    - errcheck
    - gosec
    - nilerr
    - noctx
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - wastedassign
formatters:
  enable:
    - gofmt
    - goimports
